apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ambassador-jwt.fullname" . }}
  labels:
    {{- include "ambassador-jwt.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ambassador-jwt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ambassador-jwt.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
