
replicaCount: 1

image:
  repository: ambassador-jwt
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

dnsZone: ""

azure:
  tenantID: ""
  clientID: ""
  secret: ""