micronaut:
  application:
    name: ambassadorJwt
  security:
    enabled: true
    token:
      jwt:
        signatures:
          jwks:
            this-name-doesnt-matter:
              url: https://login.microsoftonline.com/${TENANTID}/discovery/v2.0/keys
      name-key: name
